name: docker, ci/cd, ec2, hub

on: 
    push:
        branches:
            - dev

jobs:
    docker-cicd:
        runs-on: ubuntu-latest
        steps:
            # 소스코드 체크아웃
            - name: 소스코드 checkout
              uses: actions/checkout@v4

            # jdk17 설치
            - name: jdk 17 설치
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '17'

            # 필요 시 현재까지 환경 수시 확인 가능 -> 리눅스 명령어 (로그 체크)
            - name: 현재 상황 체크
              run: |
                  pwd
                  ls

            # 환경변수 동적 세팅 X (여기서는 제외)
            # 빌드, 단위 테스트 -> 도커 파일에서 진행(생략)

            # 도커 관련 액션 -> 도커 작업을 위한 환경
            - name: 도커 작업을 진행하기 위한 액션 적용
              uses: docker/setup-buildx-action@v3

            # 도커 허브 -> 프로필 -> ... -> 액세스 토큰 발급
            # 토큰 발급 : 프로필 -> account settings -> security -> personal access token
            #           -> Generate new access token -> 설정(이름, 기간, 권한) 후 generate
            # 도커 허브 로그인 -> 계정 정보 ->
            # 시크릿 변수(깃허브 : HUB_DOCKER_TOKEN, HUB_DOCKER_NAME, EC2_HOST, EC2_USER, EC2_KEY)
            - name: 도커 허브 로그인
              run: echo "${{secrets.HUB_DOCKER_TOKEN}}" | docker login -u "${{secrets.HUB_DOCKER_NAME}}" --password-stdin

            # 백엔드 이미지 생성 -> 허브(레퍼지토리) 푸시
            - name: 백엔드 이미지 생성 -> 허브(레퍼지토리) 푸시
              run: |
                docker build -t ganghyoun/demo_backend ./backend
                docket push ganghyoun/demo_backend

            # 프론트 이미지 생성 -> 허브(레퍼지토리) 푸시
            - name: 프론트 이미지 생성 -> 허브(레퍼지토리) 푸시
              run: |
                docker build -t ganghyoun/demo_frontend ./frontend
                docket push ganghyoun/demo_frontend

            # EC2 서버로 필요한 파일 업로드(yml, nginx/*.conf)

    #deploy:
        # 도커 컴포즈 진행 (배포)